name: DAST Demo Env

on:
  workflow_dispatch:
jobs:
  dast:
    runs-on: ["self-hosted", "EasyBuggy"]
    name: DAST on Prem Testing Action
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.pull_request.head.sha }}
      - name: Checkmarx DAST Github Action
        uses: Checkmarx/dast-github-action@v1.0.2
        env:
          CX_APIKEY: ${{ secrets.AST_API_KEY }}
        with:
          command: web
          config: ${{ github.event.pull_request.head.sha }}/dast-config/zap_config.yaml
          environment_id: cc5db649-16e0-4a39-8557-5eae3c7208fd
          log_level: info
          base_url: https://deu.ast.checkmarx.net/
          verbose: true      
